/**
 * Barrel export for all CLASSY foundation types.
 *
 * Usage:
 *   import type { StudentProfile, AdmissionRule, DataSource } from "@/types";
 */

export * from "./foundation";
export * from "./rules";
export * from "./provenance";
export * from "./school";
export * from "./college";

/** Academic insight type — generated by the insights engine. */
export interface AcademicInsight {
  category: "overall" | "subject" | "distribution" | "pathway";
  title: string;
  description: string;
  importance: "info" | "positive" | "warning";
}
